Add handles search post endpoint
koralabs/handles-public-api pull request #91
Opened 2024-06-04 21:49 UTC by bigirishlion

2024-06-04 22:01 UTC, papag00se requested changes

2024-06-04 22:01 UTC, papag00se commented on src/routes/handles.route.ts
> +        this.router.post(`${this.path}/search`, this.injectRegistryMiddleware, this.handlesController.search);
After thinking on this, I think `/list` is appropriate for this endpoint. I can explain more when we chat, but basically, you can either start from the full list of Handles (`/handles`) or you can start from a predefined list of Handles (`/handles/list`) and from there all of the current filter params work from the query string.

2024-06-04 22:07 UTC, papag00se commented on src/repositories/memory/handles.repository.ts
> +
I think these two can combine.

Also, I think doing the hex search this way could break for Handles that ARE hex

2024-06-05 18:11 UTC, bigirishlion commented on src/controllers/handles.controller.ts
> +                og
Good catch!

2024-06-05 18:17 UTC, bigirishlion commented on src/controllers/handles.controller.ts
> +            res.set('x-handles-search-total', result.searchTotal.toString())
Yup. I'll fix it

2024-06-06 17:44 UTC, merged